### ISSUE TITLE
Old Feature didn't added.

### ISSUE THREAD

**Issue by OPADILOP** [DevMC-org/DevMC#8]
When we hover our mouse to the item it was showed the display name and the lores too. But now the feature isn't there.

**Comment by MrFireSword** [comment]
Hello 
I can confirm it's still not working today 
were you able to add it ?

**Comment by Xezard** [comment]
I will add this soon. Thank you.

**Comment by MrFireSword** [comment]
really good job on the new UI ! 
it looks sick

**Comment by Xezard** [comment]
Feature added now.

![image](https://user-images.githubusercontent.com/17483454/210444960-531f50d1-a057-4611-9173-67c559806c34.png)
