### ISSUE TITLE
heads

### ISSUE THREAD

**Issue by Faustyu1** [DevMC-org/DevMC#9]
добавьте предпросмотр головы 
![image](https://user-images.githubusercontent.com/104709162/205455384-79f9e9e0-0db4-4ff0-8205-c9de002e2f14.png)
![image](https://user-images.githubusercontent.com/104709162/205455391-ae10c6b3-07e8-424c-bae7-c2674419e618.png)

**Comment by Xezard** [comment]
Предпросмотр голов, возможно, будет сделан в будущем. 
Сейчас в списке того, что нужно сделать, по приоритету - это стоит едва ли не на последнем месте.
